# Generated by Django 4.0.4 on 2022-04-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creditor', to='account.accountdetails')),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debitor', to='account.accountdetails')),
            ],
        ),
    ]
